apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-app-conf
  namespace: kiii
data:
  POSTGRES_URL: jdbc:postgresql://kiii-postgres-service:5432/employeeDB
  POSTGRES_DATABASE: employeeDB
  POSTGRES_USER: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secret
  namespace: kiii
type: Opaque
data:
  POSTGRES_PASSWORD: b3JhbmdlbGlvbg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
  namespace: kiii
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employeeapp
  template:
    metadata:
      labels:
        app: employeeapp
    spec:
      containers:
        - name: employee-app-container
          image: kbogojoska02/kiii-project-ci:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
#              cpu: "500m"
            requests:
              memory: "256Mi"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: employee-app-conf
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-app-secret
                  key: POSTGRES_PASSWORD